#define LAYOUT_wrapper_ortho_4x12(...) LAYOUT_ortho_4x12(__VA_ARGS__)

#define BASE \
__BASE_NUMPAD_1_1__,   __BASE_NUMPAD_2_1__,  __BASE_NUMPAD_3_1__, \
__BASE_NUMPAD_1_2__,   __BASE_NUMPAD_2_2__,  __BASE_NUMPAD_3_2__, \
__BASE_NUMPAD_1_3__,   __BASE_NUMPAD_2_3__,  __BASE_NUMPAD_3_3__, \
__BASE_NUMPAD_1_4__,   __BASE_NUMPAD_2_4__,  __BASE_NUMPAD_3_4__

#define RAISE \
__BASE_NUMPAD_1_1__,   __BASE_NUMPAD_2_1__,  __BASE_NUMPAD_3_1__, \
__BASE_NUMPAD_1_2__,   __BASE_NUMPAD_2_2__,  __BASE_NUMPAD_3_2__, \
__BASE_NUMPAD_1_3__,   __BASE_NUMPAD_2_3__,  __BASE_NUMPAD_3_3__, \
__BASE_NUMPAD_1_4__,   __BASE_NUMPAD_2_4__,  __BASE_NUMPAD_3_4__

#define LOWER \
__BASE_NUMPAD_1_1__,   __BASE_NUMPAD_2_1__,  __BASE_NUMPAD_3_1__, \
__BASE_NUMPAD_1_2__,   __BASE_NUMPAD_2_2__,  __BASE_NUMPAD_3_2__, \
__BASE_NUMPAD_1_3__,   __BASE_NUMPAD_2_3__,  __BASE_NUMPAD_3_3__, \
__BASE_NUMPAD_1_4__,   __BASE_NUMPAD_2_4__,  __BASE_NUMPAD_3_4__
