name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
# List of keymap json files to build
        file:
        - lily58.json
        - crkbd.json
        - iris.json
        - ergodox.json
        - preonic.json
        - planck-v6.json
        - sweet16.json

# End of json file list

    steps:
    - name: Disable git safe directory checks
      run: git config --global --add safe.directory '*'
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
# Uncomment the following for develop branch
#        ref: develop
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}

    - name: Build firmware
      run: qmk compile -j 8 "users/${{ github.actor }}/${{ matrix.file }}"

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.file }}_${{ github.actor }}
        retention-days: 90
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true

  build-kb2040:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
# List of keymap json files to build
        file:
        - lily58.json
        - crkbd.json
        - skeletyl.json
# End of json file list

    steps:

    - name: Disable git safe directory checks
      run: git config --global --add safe.directory '*'
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
# Uncomment the following for develop branch
#        ref: develop
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}

    - name: Build firmware
      run: qmk compile -j 16 "users/${{ github.actor }}/${{ matrix.file }}" -e CONVERT_TO=kb2040

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.file }}_${{ github.actor }}_kb2040
        retention-days: 90
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true

  build-bkb-splinky:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
# List of keymap json files to build
        file:
        - chary.json
# End of json file list

    steps:

    - name: Disable git safe directory checks
      run: git config --global --add safe.directory '*'
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: Bastardkb/bastardkb-qmk
# Uncomment the following for develop branch
        ref: bkb-master
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}

    - name: Build firmware
      run: cp users/ridingintraffic/chary_info.json keyboards/bastardkb/charybdis/3x5/info.json; qmk compile -j 16 "users/${{ github.actor }}/${{ matrix.file }}"

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.file }}_${{ github.actor }}
        retention-days: 90
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true
  build-fingerpunch:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
# List of keymap json files to build
        file:
        - ffkb.json
        - rockon.json

# End of json file list

    steps:

    - name: Disable git safe directory checks
      run: git config --global --add safe.directory '*'
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: sadekbaroudi/qmk_firmware
# Uncomment the following for develop branch
        ref: master
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}

    - name: Build firmware
      run: qmk compile -j 16 "users/${{ github.actor }}/${{ matrix.file }}" -e FP_EVQ_UNDER_PALMS=yes -e  RGB_MATRIX_ENABLE=yes

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.file }}_${{ github.actor }}
        retention-days: 90
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true
  build-fingerpunch-sweep:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
# List of keymap json files to build
        file:
        - sweep.json

# End of json file list

    steps:
    - name: Disable git safe directory checks
      run: git config --global --add safe.directory '*'
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: sadekbaroudi/qmk_firmware
# Uncomment the following for develop branch
        ref: master
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}

    - name: Build firmware
      run: qmk compile -j 16 "users/${{ github.actor }}/${{ matrix.file }}" -e CONVERT_TO=elite_pi

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.file }}_${{ github.actor }}
        retention-days: 90
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true
  build-fingerpunch-stemcell:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
# List of keymap json files to build
        file:
        - ffkb.json

# End of json file list

    steps:

    - name: Disable git safe directory checks
      run: git config --global --add safe.directory '*'
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: sadekbaroudi/qmk_firmware
# Uncomment the following for develop branch
        ref: develop_fingerpunch
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}

    - name: Build firmware
      run: qmk compile -j 16 "users/${{ github.actor }}/${{ matrix.file }}" -e CONVERT_TO=stemcell -e FP_EVQ_UNDER_PALMS=yes -e RGBLIGHT_ENABLE=yes

    - name: Archive firmware
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.file }}_${{ github.actor }}
        retention-days: 90
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true

